[build]
command = "cd frontend && npm install && npm run build"

[build.upload]
format = "directory"

[pages]
build_output_directory = "frontend/dist"

[functions]
directory = "functions"

[site]
bucket = "frontend/dist"

[env.production]
vars = { NODE_ENV = "production" }

# Environment variables for MongoDB connection
# These will be replaced with actual values in Cloudflare dashboard
[vars]
MONGODB_URI = "mongodb+srv://username:password@cluster.mongodb.net/edusoft"
JWT_SECRET = "your_jwt_secret_here"

[[routes]]
pattern = "/api/*"
script = "functions/api/[[path]].js"

[[routes]]
pattern = "/api/supervisors/*"
script = "functions/api/supervisors/[[path]].js" 