# Cloudflare Pages configuration

# Compatibility flags
compatibility_flags = []

# Compatibility date
compatibility_date = "2023-11-01"

# Functions configuration
[functions]
directory = "/functions"
included_files = ["**/*.js", "**/*.mjs"]
node_compat = true

# Build configuration
[build]
command = "cd frontend && npm install && npm run build"
output_directory = "frontend/dist"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "frontend/dist"
entry-point = "frontend/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.upload]
format = "directory" 