[build]
command = "cd frontend && npm install && npm run build"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "frontend/dist"
entry-point = "frontend/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 